### ISSUE TITLE
Order does not exist

### ISSUE THREAD

**Issue by JulienDev** [tony-ho/binance-oco#26] opened 2021-01-23 10:16 UTC
Hello Tony,
Awesome script, thank you for your crazy work!

Very often (50% of the time) I have an issue when I place a buy order followed by an OCO. I've noticed that the order is sent to Binance (appears in my orders list) but then your script is not able to find the order on Binance. I suspect your script is too fast and  should wait few milliseconds/seconds before going to the next step. Here is an example : 

```
binance-oco -p NEOUSDT -a 19 -b 23.01 -s 22.43 -t 23.70                                            
  binance-oco Validating stop order: { symbol: 'NEOUSDT', side: 'SELL', quantity: '19.000', price: '4.870', stopPrice: '22.430', type: 'STOP_LOSS_LIMIT' } +0ms
  binance-oco Stop order valid +281ms
  binance-oco Validating target order: { symbol: 'NEOUSDT', side: 'SELL', quantity: '19.000', price: '23.700', type: 'LIMIT' } +1ms
  binance-oco Target order valid +251ms
  binance-oco NEOUSDT price: 24.32000000 +258ms
  binance-oco Buy response: { symbol: 'NEOUSDT', orderId: 370401142, orderListId: -1, clientOrderId: 'keVtUj4bf7AYxnTiN4gMco', transactTime: 1611396491263, price: '23.01000000', origQty: '19.00000000', executedQty: '0.00000000', cummulativeQuoteQty: '0.00000000', status: 'NEW', timeInForce: 'GTC', type: 'LIMIT', side: 'BUY', fills: [] } +265ms
  binance-oco order id: 370401142 +0ms
/usr/local/lib/node_modules/binance-oco/node_modules/binance-api-node/dist/http-client.js:59
        error = new Error(json.msg || "".concat(res.status, " ").concat(res.statusText));
                ^

Error: Order does not exist.
    at /usr/local/lib/node_modules/binance-oco/node_modules/binance-api-node/dist/http-client.js:59:17
    at processTicksAndRejections (node:internal/process/task_queues:94:5) {
  code: -2013,
  url: 'https://api.binance.com/api/v3/order?symbol=NEOUSDT&orderId=370401142&timestamp=1611396491331&signature=ce0986ef0fd12aca548861ae53fa607fe47b8024a79b76cb925a4aeb561f7e9b'
}
```

**Comment by tony-ho** [comment] 2021-01-26 10:58
@JulienDev Thanks for raising this issue.

I haven't been able to reliably reproduce the error, but believe it is the same issue raised here: https://dev.binance.vision/t/faq-error-message-order-does-not-exist/46

This should be resolved in [v3.1.2](https://github.com/tony-ho/binance-oco/releases/tag/v3.1.2).

Let me know if you continue to encounter this error after updating.

**Comment by JulienDev** [comment] 2021-01-26 13:17
The issue is still present in 3.1.2:

```
pi@raspberrypi:~ $ binance-oco -p ZILUSDT -a 16000 -b 0.0633 -s 0.0614 -t 0.06528
  binance-oco Validating stop order: { symbol: 'ZILUSDT', side: 'SELL', quantity: '16000.0', price: '0.01281', stopPrice: '0.06140', type: 'STOP_LOSS_LIMIT' } +0ms
  binance-oco Stop order valid +307ms
  binance-oco Validating target order: { symbol: 'ZILUSDT', side: 'SELL', quantity: '16000.0', price: '0.06528', type: 'LIMIT' } +1ms
  binance-oco Target order valid +314ms
  binance-oco ZILUSDT price: 0.06414000 +291ms
  binance-oco Buy response: { symbol: 'ZILUSDT', orderId: 168368567, orderListId: -1, clientOrderId: 'hK3zrRNAZcU4SXmckUNIdo', transactTime: 1611666825214, price: '0.06330000', origQty: '16000.00000000', executedQty: '0.00000000', cummulativeQuoteQty: '0.00000000', status: 'NEW', timeInForce: 'GTC', type: 'LIMIT', side: 'BUY', fills: [] } +300ms
  binance-oco order id: 168368567 +2ms
/usr/lib/node_modules/binance-oco/node_modules/binance-api-node/dist/http-client.js:59
        error = new Error(json.msg || "".concat(res.status, " ").concat(res.statusText));
                ^

Error: Order does not exist.
    at /usr/lib/node_modules/binance-oco/node_modules/binance-api-node/dist/http-client.js:59:17
    at processTicksAndRejections (node:internal/process/task_queues:94:5) {
  code: -2013,
  url: 'https://api.binance.com/api/v3/order?symbol=ZILUSDT&orderId=168368567&timestamp=1611666825345&signature=ec9b1cc0f0ef8e3b73a0761ae624d33689f42c6708c3b3a4a77b2b0701b3fa84'
}
```

**Closed** 2021-02-16 11:41 UTC
Labels: bug, released

**Comment by tony-ho** [comment] 2021-02-16 11:48
@JulienDev Looks like there was a bug in the error handling which is now resolved.

Can you try again using [v3.1.3](https://github.com/tony-ho/binance-oco/releases/tag/v3.1.3)?

**Comment by JulienDev** [comment] 2021-03-21 15:21
After few weeks using it, I confirm it's working pretty well ! Thank you Tony !
